CREATE CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
UNWIND [{_id:1, properties:{interval:["1960—Now"], title:"Name"}}, {_id:4, properties:{interval:["1960—Now"], title:"Name"}}, {_id:7, properties:{interval:["1960—Now"], title:"Name"}}, {_id:41, properties:{interval:["1988—Now"], title:"Name"}}, {_id:44, properties:{interval:["1976—Now"], title:"Name"}}, {_id:55, properties:{interval:["2009—Now"], title:"Name"}}, {_id:58, properties:{interval:["1960—Now"], title:"Name"}}, {_id:61, properties:{interval:["1960—Now"], title:"Name"}}, {_id:64, properties:{interval:["1977—Now"], title:"Name"}}, {_id:67, properties:{interval:["2012—Now"], title:"Name"}}, {_id:70, properties:{interval:["1999—Now"], title:"Name"}}, {_id:73, properties:{interval:["1975—Now"], title:"Name"}}, {_id:76, properties:{interval:["2009—Now"], title:"Name"}}, {_id:79, properties:{interval:["2007—Now"], title:"Name"}}, {_id:81, properties:{interval:["1999—Now"], title:"Name"}}] as row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Attribute;
UNWIND [{_id:0, properties:{interval:["1960—Now"], title:"City"}}, {_id:3, properties:{interval:["1960—Now"], title:"City"}}, {_id:6, properties:{interval:["1960—Now"], title:"City"}}, {_id:20, properties:{interval:["1960—Now"], title:"City"}}, {_id:40, properties:{interval:["1988—Now"], title:"Person"}}, {_id:43, properties:{interval:["1976—Now"], title:"Person"}}, {_id:54, properties:{interval:["2009—Now"], title:"Person"}}, {_id:60, properties:{interval:["1960—Now"], title:"City"}}, {_id:63, properties:{interval:["1977—Now"], title:"Person"}}, {_id:66, properties:{interval:["2012—Now"], title:"Person"}}, {_id:69, properties:{interval:["1999—Now"], title:"Person"}}, {_id:72, properties:{interval:["1975—Now"], title:"Person"}}, {_id:75, properties:{interval:["2009—Now"], title:"Person"}}, {_id:78, properties:{interval:["2007—Now"], title:"Person"}}, {_id:98, properties:{interval:["1999—Now"], title:"Person"}}] as row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Object;
UNWIND [{_id:2, properties:{interval:["1960—Now"], value:"South Josphine"}}, {_id:5, properties:{interval:["1960—Now"], value:"Lake Silvaville"}}, {_id:8, properties:{interval:["1960—Now"], value:"Zenaview"}}, {_id:42, properties:{interval:["1988—Now"], value:"Marica Koepp"}}, {_id:53, properties:{interval:["1976—Now"], value:"Felipe Howe"}}, {_id:56, properties:{interval:["2009—Now"], value:"Jamila Herzog"}}, {_id:59, properties:{interval:["1960—Now"], value:"New Denis"}}, {_id:62, properties:{interval:["1960—Now"], value:"Lake Javier"}}, {_id:65, properties:{interval:["1977—Now"], value:"Shelby Jenkins I"}}, {_id:68, properties:{interval:["2012—Now"], value:"Edda Jaskolski"}}, {_id:71, properties:{interval:["1999—Now"], value:"Roland Emard"}}, {_id:74, properties:{interval:["1975—Now"], value:"Jamaal Jenkins"}}, {_id:77, properties:{interval:["2009—Now"], value:"Sanford Johnson"}}, {_id:80, properties:{interval:["2007—Now"], value:"Miss Hayden Spinka"}}, {_id:82, properties:{interval:["1999—Now"], value:"Austin Klocko"}}] as row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Value;
UNWIND [{start: {_id:1}, end: {_id:2}, properties:{}}, {start: {_id:4}, end: {_id:5}, properties:{}}, {start: {_id:7}, end: {_id:8}, properties:{}}, {start: {_id:41}, end: {_id:42}, properties:{}}, {start: {_id:44}, end: {_id:53}, properties:{}}, {start: {_id:58}, end: {_id:59}, properties:{}}, {start: {_id:61}, end: {_id:62}, properties:{}}, {start: {_id:64}, end: {_id:65}, properties:{}}, {start: {_id:67}, end: {_id:68}, properties:{}}, {start: {_id:70}, end: {_id:71}, properties:{}}, {start: {_id:73}, end: {_id:74}, properties:{}}, {start: {_id:55}, end: {_id:56}, properties:{}}, {start: {_id:76}, end: {_id:77}, properties:{}}, {start: {_id:79}, end: {_id:80}, properties:{}}, {start: {_id:81}, end: {_id:82}, properties:{}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Edge]->(end) SET r += row.properties;
UNWIND [{start: {_id:69}, end: {_id:72}, properties:{interval:["2016—Now"]}}, {start: {_id:54}, end: {_id:78}, properties:{interval:["2018—Now"]}}, {start: {_id:72}, end: {_id:43}, properties:{interval:["2009—2015"]}}, {start: {_id:72}, end: {_id:66}, properties:{interval:["2017—Now"]}}, {start: {_id:40}, end: {_id:72}, properties:{interval: ["2009—2014","2017—2018"]}}, {start: {_id:78}, end: {_id:43}, properties:{interval:["2011—2013","2015—2016"]}}, {start: {_id:78}, end: {_id:63}, properties:{interval:["2013—2016","2018—Now"]}}, {start: {_id:63}, end: {_id:40}, properties:{interval:["1989—2011","2017—2018"]}}, {start: {_id:66}, end: {_id:40}, properties:{interval:["2012—2016"]}}, {start: {_id:66}, end: {_id:54}, properties:{interval:["2013—2015"]}}, {start: {_id:98}, end: {_id:78}, properties:{interval:["2017—2018"]}}, {start: {_id:43}, end: {_id:69}, properties:{interval:["2003—2004"]}}, {start: {_id:75}, end: {_id:69}, properties:{interval:["2014—Now"]}}, {start: {_id:75}, end: {_id:78}, properties:{interval:["2013—2014","2018—Now"]}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Friend]->(end) SET r += row.properties;
UNWIND [{start: {_id:72}, end: {_id:3}, properties:{interval:["1975—Now"]}}, {start: {_id:40}, end: {_id:60}, properties:{interval:["1988—Now"]}}, {start: {_id:43}, end: {_id:3}, properties:{interval:["1976—Now"]}}, {start: {_id:63}, end: {_id:3}, properties:{interval:["1977—Now"]}}, {start: {_id:66}, end: {_id:20}, properties:{interval:["2012—Now"]}}, {start: {_id:69}, end: {_id:3}, properties:{interval:["1999—Now"]}}, {start: {_id:54}, end: {_id:20}, properties:{interval:["2009—Now"]}}, {start: {_id:75}, end: {_id:6}, properties:{interval:["2009—Now"]}}, {start: {_id:78}, end: {_id:3}, properties:{interval:["2007—Now"]}}, {start: {_id:98}, end: {_id:60}, properties:{interval:["1999—Now"]}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:LivedIn]->(end) SET r += row.properties;
UNWIND [{start: {_id:0}, end: {_id:1}, properties:{}}, {start: {_id:3}, end: {_id:4}, properties:{}}, {start: {_id:6}, end: {_id:7}, properties:{}}, {start: {_id:20}, end: {_id:58}, properties:{}}, {start: {_id:40}, end: {_id:41}, properties:{}}, {start: {_id:43}, end: {_id:44}, properties:{}}, {start: {_id:60}, end: {_id:61}, properties:{}}, {start: {_id:63}, end: {_id:64}, properties:{}}, {start: {_id:66}, end: {_id:67}, properties:{}}, {start: {_id:69}, end: {_id:70}, properties:{}}, {start: {_id:72}, end: {_id:73}, properties:{}}, {start: {_id:54}, end: {_id:55}, properties:{}}, {start: {_id:75}, end: {_id:76}, properties:{}}, {start: {_id:78}, end: {_id:79}, properties:{}}, {start: {_id:98}, end: {_id:81}, properties:{}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Edge]->(end) SET r += row.properties;
MATCH (n:`UNIQUE IMPORT LABEL`)  WITH n LIMIT 20000 REMOVE n:`UNIQUE IMPORT LABEL` REMOVE n.`UNIQUE IMPORT ID`;
DROP CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
